version: '2'

services:
  sonarqube:
    image: sonarqube:8.3.1-community
    depends_on:
      - db
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
  db:
    image: postgres:11.6
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_HOST_AUTH_METHOD: trust

    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_data: ~/volumes/sonarqube/sonar/data
  sonarqube_extensions: ~/volumes/sonarqube/sonar/extensions
  sonarqube_logs: ~/volumes/sonarqube/sonar/logs
  sonarqube_temp: ~/volumes/sonarqube/sonar/temp
  postgresql:
    driver: local
  postgresql_data: ~/volumes/sonarqube/postgresql/data